using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace HoryTweaks.Generators;

/// <summary>
/// Emits the assembly version (from the MSBuild <c>Version</c> property) as a compile-time
/// constant so the plugin has a single source of truth for its version.
/// </summary>
[Generator]
public sealed class BuildInfoGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MissingVersion = new(
        id: "HTG003",
        title: "MSBuild Version property is missing",
        messageFormat: "Cannot generate BuildInfo: the 'Version' MSBuild property is absent or empty",
        category: "HoryTweaks.Generators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var version = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
            provider.GlobalOptions.TryGetValue("build_property.Version", out var value) ? value : null);

        context.RegisterSourceOutput(version, static (sourceContext, value) =>
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                sourceContext.ReportDiagnostic(Diagnostic.Create(MissingVersion, Location.None));
                return;
            }

            var source = $$"""
                // <auto-generated />
                namespace HoryTweaks;

                internal static class BuildInfo
                {
                    internal const string Version = "{{value}}";
                }
                """;

            sourceContext.AddSource("BuildInfo.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
}
