<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<AssemblyName>HoryTweaks.Core</AssemblyName>
		<RootNamespace>HoryTweaks.Core</RootNamespace>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Semver" />
	</ItemGroup>
</Project>
